/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Iwq391i0dcP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function HeroDreamJob() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid gap-10 md:grid-cols-2">
        <div className="space-y-4">
          <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Job Search Tips</div>
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Find Your Dream Job</h2>
          <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Discover practical tips to help you stand out in the job market and land your ideal role.
          </p>
        </div>
        <div className="space-y-4">
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <ListRestartIcon className="h-6 w-6 text-primary" />
              <p className="font-medium">Update your resume</p>
            </div>
            <p className="text-muted-foreground">
              Highlight your relevant skills and experience. Consider getting your resume reviewed by a professional.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <NetworkIcon className="h-6 w-6 text-primary" />
              <p className="font-medium">Network</p>
            </div>
            <p className="text-muted-foreground">
              Reach out to former colleagues, attend industry events, and use LinkedIn to connect with potential
              contacts.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <SearchIcon className="h-6 w-6 text-primary" />
              <p className="font-medium">Search job boards</p>
            </div>
            <p className="text-muted-foreground">
              Search job boards and company websites for open positions that match your qualifications.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <VideoIcon className="h-6 w-6 text-primary" />
              <p className="font-medium">Prepare for interviews</p>
            </div>
            <p className="text-muted-foreground">Practice common questions and research the company.</p>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <LinkedinIcon className="h-6 w-6 text-primary" />
              <p className="font-medium">Work with a recruiter</p>
            </div>
            <p className="text-muted-foreground">
              Consider working with a recruiter or career coach who can provide guidance and connect you with
              opportunities.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center gap-4">
              <PointerIcon className="h-6 w-6 text-primary" />
              <p className="font-medium">Be persistent</p>
            </div>
            <p className="text-muted-foreground">
              Don't get discouraged - finding the right job takes time and effort.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function ListRestartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 6H3" />
      <path d="M7 12H3" />
      <path d="M7 18H3" />
      <path d="M12 18a5 5 0 0 0 9-3 4.5 4.5 0 0 0-4.5-4.5c-1.33 0-2.54.54-3.41 1.41L11 14" />
      <path d="M11 10v4h4" />
    </svg>
  )
}


function NetworkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function PointerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 14a8 8 0 0 1-8 8" />
      <path d="M18 11v-1a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0" />
      <path d="M14 10V9a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v1" />
      <path d="M10 9.5V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v10" />
      <path d="M18 11a2 2 0 1 1 4 0v3a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
